### ISSUE TITLE
PVPUI 的征服点数进度条看不到进度

### ISSUE THREAD

**Issue by Solor** [siweia/AuroraClassic#12]
这两个进度条的进度材质没有正确显示。

```HonorFrame.ConquestBar```
```ConquestFrame.ConquestBar```

![wow 2018-09-08 02-07-54](https://user-images.githubusercontent.com/156806/45235991-2e727580-b30d-11e8-9071-e1027af6248d.jpg)

另外 WarBoardUI 没有美化，比如主城的公告板和进入激流堡战役的那个公告板。

**Comment by siweia** [comment]
warboardui我有改动它的字体吧，因为默认UI感觉没有什么美化的必要。就跟新的桌子我保留了阵营logo一样。

**Comment by Solor** [comment]
新桌子那个阵营标志丑爆了，我自己隐藏了，还以为你是忘了 🤣
