### ISSUE TITLE
激流堡战役相关的一些界面元素没有美化

### ISSUE THREAD

**Issue by Solor** [siweia/AuroraClassic#13]
建筑tooltip上的图标和进度条以及任务追踪栏上的场景战役block

![ttt](https://user-images.githubusercontent.com/156806/45878456-ae9bdf00-bdd3-11e8-824b-dace4b3c5aed.jpg)

**Comment by siweia** [comment]
我得等到轮到部落才能测试，上次注意到了，但是没来得及弄。
