### ISSUE TITLE
Unable to socket follower equipment.

### ISSUE THREAD

**Issue by tordenflesk** [siweia/AuroraClassic#14]
https://i.imgur.com/fo2qPsf.png

**Comment by siweia** [comment]
Type cmd "/console taintLog 1", and re-socket your follower equipment.
And post me the file in wow/logs/taint.log.
I just made a follower equip by Engineering myself, it was all fine.

**Comment by tordenflesk** [comment]
9/26 15:49:02.978  Global variable LE_ITEM_QUALITY_COMMON tainted by AuroraClassic - `ü=:2
9/26 15:49:02.978  Execution tainted by AuroraClassic while reading LE_ITEM_QUALITY_COMMON - Interface\FrameXML\ItemButtonTemplate.lua:124 SetItemButtonQuality()
9/26 15:49:02.978      Interface\FrameXML\TradeFrame.lua:105 TradeFrame_UpdatePlayerItem()
9/26 15:49:02.978      Interface\FrameXML\TradeFrame.lua:71 TradeFrame_Update()
9/26 15:49:02.978      Interface\FrameXML\TradeFrame.lua:40
9/26 15:49:02.978      GetItemInfo()
9/26 15:49:02.978      Interface\FrameXML\ChatFrame.lua:1047
9/26 15:49:02.978  Interface\FrameXML\StaticPopup.lua:4941 StaticPopup_OnClick()
9/26 15:49:02.978  An action was blocked because of taint from AuroraClassic - CastItemSpellOnFollowerAbility()
9/26 15:49:02.978      Interface\AddOns\Blizzard_GarrisonTemplates\Blizzard_GarrisonSharedTemplates.lua:59 OnAccept()
9/26 15:49:02.978      Interface\FrameXML\StaticPopup.lua:4973 StaticPopup_OnClick()
9/26 15:49:02.978      StaticPopup1Button1:OnClick()

**Comment by siweia** [comment]
I can't replicate the error. What equipment exactly is that cause the problem?

**Comment by tordenflesk** [comment]
Disenchanting Rod & Kaleidoscopic Lens
