### ISSUE TITLE
Border frame for Bank

### ISSUE THREAD

**Issue by Urguk** [siweia/AuroraClassic#18]
Thank you for the fix for the Zygor issue. However I'm seeing the same now for the bank, but if bag is check in configuration it is skinned instead. Unchecked it is  not. It is just the bank window that showing it not the bags when opened.

**Comment by siweia** [comment]
Is it caused by Zygor as well?

**Comment by Urguk** [comment]
I do not think so. It was not happening before the fix was made.  I'll do
some testing with it disable today.

**Comment by Urguk** [comment]
I show up when I disable Zygor and all other modes that I have installed. Here is the screen grab with Zygor disable. 

![wowscrnshot_010819_103432](https://user-images.githubusercontent.com/369974/50849196-46521880-1344-11e9-801e-b411a2d6ab3e.jpg)

**Comment by siweia** [comment]
Bankframe won't be reskinned if unchecked the "bags" checkbox.
It is actually "blame" to Altzui. What you can do is to put the code below under line 116.
`	BankFrame.NineSlice:Hide()
	BankFrameMoneyFrameInset.NineSlice:Hide()`
https://github.com/Paojy/Altz-UI/blob/c5f1cad319059bfcce4dbc8efdce92a80638f668/Interface/AddOns/AltzUI/mods/bag/bags.lua#L116

**Comment by Urguk** [comment]
ah thank you I'll do that.

**Comment by Urguk** [comment]
that fix the issue. you can close out the issue ticket as it is not a
AuroraClassic causing the problem.
