### ISSUE TITLE
WarboardQuestChoiceFrame 在激活时的一个报错

### ISSUE THREAD

**Issue by neavo** [siweia/AuroraClassic#23]
WarboardQuestChoiceFrame 在激活时会有一个报错，可以通过要塞的任务桌稳定触发。

具体原因是 \AddOns\Blizzard_QuestChoice.lua 中 self.numActiveOptionFrames 字段不存在，正确的方法是通过 self:GetNumOptions() 来获取激活的面板的数量。

问题比较简单，就不发PR了，请手动修正一下吧。

**Comment by siweia** [comment]
https://www.townlong-yak.com/framexml/30920/QuestChoiceFrameMixin.lua/diff
看来8.2就改了
