### ISSUE TITLE
聊天气泡的边框染色能否直接获取文字自己的颜色？

### ISSUE THREAD

**Issue by Solor** [siweia/AuroraClassic#3]
b24f5bd359de7af5a864bd5bb2943d984088a665 使用预定义的颜色会有个问题，比如我的 say 是淡蓝色 yell 是粉色，就会出现文字和边框染色不符的情况，能否直接获取文字自己的颜色来染色边框 😢

**Comment by Solor** [comment]
另外染色没有正确的update，比如上次是 say，下次 yell 则还是 say 的染色 🥂

**Comment by Solor** [comment]
染色正常了，感谢更新 
染色类型还少了一种，NPC 的普通说话，淡黄色的那种 😍

**Comment by siweia** [comment]
npc就不管了，黑色。
