### ISSUE TITLE
AuroraClassic\FrameXML\QuestInfo.lua:12: attempt to index field 'bg' (a nil value)

### ISSUE THREAD

**Issue by tordenflesk** [siweia/AuroraClassic#8]
3x AuroraClassic\FrameXML\QuestInfo.lua:12: attempt to index field 'bg' (a nil value)
AuroraClassic\FrameXML\QuestInfo.lua:12: in function <AuroraClassic\FrameXML\QuestInfo.lua:10>
AuroraClassic\FrameXML\QuestInfo.lua:17: in function <AuroraClassic\FrameXML\QuestInfo.lua:16>
[C]: in function `SetPoint'
FrameXML\QuestInfo.lua:40: in function <FrameXML\QuestInfo.lua:38>
AutoEquipQuestItem\Core.lua:59: in function `QuestInfoItem_OnClick'
FrameXML\QuestInfo.lua:983: in function <FrameXML\QuestInfo.lua:974>

Locals:
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = QuestInfoRewardsFrameQuestInfoItem1 {
 }
 2 = QuestInfoRewardsFrameQuestInfoItem2 {
 }
 3 = QuestInfoRewardsFrameQuestInfoItem3 {
 }
 4 = QuestInfoRewardsFrameQuestInfoItem4 {
 }
 5 = QuestInfoRewardsFrameQuestInfoItem5 {
 }
 6 = QuestInfoRewardsFrameQuestInfoItem6 {
 }
}
(for control) = 1
_ = 1
button = QuestInfoRewardsFrameQuestInfoItem1 {
 0 = <userdata>
 restyled = true
 NameFrame = QuestInfoRewardsFrameQuestInfoItem1NameFrame {
 }
 IconOverlay = <unnamed> {
 }
 count = 1
 CanIMogItOverlay = CIMIOverlayFrame_QuestInfoRewardsFrameQuestInfoItem1 {
 }
 _auroraNameBG = <unnamed> {
 }
 type = "choice"
 Count = QuestInfoRewardsFrameQuestInfoItem1Count {
 }
 IconBorder = <unnamed> {
 }
 _auroraIconBorder = <unnamed> {
 }
 objectType = "item"
 Icon = QuestInfoRewardsFrameQuestInfoItem1IconTexture {
 }
 Name = QuestInfoRewardsFrameQuestInfoItem1Name {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'bg' (a nil value)"

**Comment by Solor** [comment]
你是不是用了 Immersion，AuroraClassical 和它冲突

**Comment by tordenflesk** [comment]
Nevermind, I think i had both Aurora and AuroraClassic loaded at the same time.

**Comment by siweia** [comment]
Problem solved?
